### ISSUE TITLE
PsiClass type in unaccessible in IDEA 2019.2

### ISSUE THREAD

**Issue by Tagakov** [dkandalov/live-plugin#103]
For some strange reason I can't access PsiClas and PsiClassImpl in my LivePlugin. But, for example, com.intellij.psi.PsiElement is available.

Sample plugin code:
`val psiClass: com.intellij.psi.PsiClass? = null`

Error:
```
error: unresolved reference: PsiClass
val psiClass: com.intellij.psi.PsiClass? = null 
```

LivePlugin version: 0.6.3
IDEA version: 
```
IntelliJ IDEA 2019.2.3 (Community Edition)
Build #IC-192.6817.14, built on September 23, 2019
Runtime version: 11.0.4+10-b304.69 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.6
GC: ParNew, ConcurrentMarkSweep
Memory: 9728M
Cores: 12
Registry: java.completion.argument.hints.internal=false
Non-Bundled Plugins: String Manipulation, org.jetbrains.kotlin, LivePlugin
```

Is there any workaround to fix overcome this issue?

**Comment by Tagakov** [comment]
Looks like there is no `com.intellij.psi.PsiClass` in jars inside `ideaHomeDirectory/lib`

**Comment by Tagakov** [comment]
Also, it isn't working on 2019.3 EAP but works on 2019.1.4

**Comment by Tagakov** [comment]
I believe the issue can be solved by adding 
```
File("${LivePluginPaths.ideJarsPath}/../plugins/java/lib/").filesList() +
```
to `LivePluginScriptCompilationConfiguration#13`

**Comment by dkandalov** [comment]
I think this happens because `PsiElement` is still part of the core API and `PsiClass` was moved to a separate java-specific "plugin" called `com.intellij.java` (which overall is the right thing to do because most IDEs don't deal with java code).

Adding `// depends-on-plugin com.intellij.java` after imports in `plugin.groovy` should help.
