### ISSUE TITLE
How to register action group and set anchor

### ISSUE THREAD

**Issue by sanniou** [dkandalov/live-plugin#114]
When write a plugin project, i can register action group and set anchor and look like this.
![](https://user-images.githubusercontent.com/14797618/97777388-d7921f00-1baa-11eb-849b-7980c6c34e4c.png)
![](https://user-images.githubusercontent.com/14797618/97777525-cc8bbe80-1bab-11eb-8d06-42d32335cd14.png)
So is the way to do the same by liva-plugin？

**Comment by dkandalov** [comment]
You can try `liveplugin.PluginUtil#registerAction()` function which has `actionGroupId` but no way to specify anchor.

Also the main idea behind liveplugin is to just evaluate code inside IDE JVM. You don't have to use `liveplugin.PluginUtil` and can use IntelliJ API directly. In particular, you could lookup the action group object using `ActionManager.instance.getAction(actionGroupId)` and then use `com.intellij.openapi.actionSystem.DefaultActionGroup` class to add action to the group with the anchor (I think this is what xml config is doing under the hood anyway).

**Comment by sanniou** [comment]
work well by use `DefaultActionGroup#addAction(AnAction,Constraints)`
thank you very much !
