### ISSUE TITLE
New Kotlin plugin doesn't work, but examples work fine

### ISSUE THREAD

**Issue by eoliphan** [dkandalov/live-plugin#120]
Hi, I'm running on IDEA 2021.1.1 Ultimate and seeing some weird behavior.   If I add an example (e.g. "Kotlin Examples -> java inspection:"), everything works just fine.  I can run/modify it with no problem.  However if I create my own Kotlin plugin and just copy code from the example over, symbol resolution, etc don't work.   I've tried restarting intellij, as well as doing the "Add LivePlugin and IDE jars to Project" option, etc but the problem persists.

Interestingly, the liveplugin.* and com.intellij.openapi.project.Project refs are fine, but the PSI and codeInspection stuff isn't resolved. 

![Screen Shot 2021-05-12 at 3 51 13 PM](https://user-images.githubusercontent.com/1065736/118028843-ed428700-b339-11eb-966c-9b5583cbee9b.png)

**Comment by dkandalov** [comment]
Hi, I think the file needs `// depends-on-plugin com.intellij.java` after imports. This is because java has been refactored out of IJ core some time ago and now it's a separate plugin, e.g. just like git.

**Comment by eoliphan** [comment]
Ah heck.  That was it, didn't realize the comment was meaningful.  Thanks!
