### ISSUE TITLE
Please create a 0.7.1 release

### ISSUE THREAD

**Issue by Gribnif** [dkandalov/live-plugin#122]
My attempts at compiling it myself have failed, so could you please add a new [release](https://github.com/dkandalov/live-plugin/releases). The 0.7.0 version does not work with DataGrip 2021.2 RC.

**Comment by dkandalov** [comment]
Will do. I think the plugin is at least partially broken in all IntelliJ 2021.2 beta and RC IDEs. This is because of IntelliJ API and behaviour changes.

**Comment by dkandalov** [comment]
I published [0.7.1 release](https://github.com/dkandalov/live-plugin/releases/tag/v0.7.1beta) just waiting for jetbrains to approve it.
