### ISSUE TITLE
Importing plugins from project files

### ISSUE THREAD

**Issue by karollewandowski** [dkandalov/live-plugin#126]
Hi, I think it would be great to have the possibility of sharing live plugins specific to some project as part of this project sources or configuration.

This combined with defining LivePlugin as required in **Build, Execution, Deployment | Required Plugins** would be a very neat feature. All team members could use and contribute to a project-specific functionality without the need of manual checking out plugin scripts from GitHub or disk.

**Comment by dkandalov** [comment]
Hi. In the plugin tool window there is `Run Project Specific Plugins` checkbox. When enabled, it will run all plugins in `.live-plugins` project directory when the project is opened and unload them when the project is closed. It's mentioned in the readme but I guess it's not obvious enough, so probably worth updating the docs 🤔 

I didn't know about the **Required Plugins** feature, thank you!

**Comment by karollewandowski** [comment]
My bad, I totally missed this part in the README 😳

Thanks for the clarification and sorry for bothering you. I'm closing the issue then.

**Comment by dkandalov** [comment]
No problem at all! It's really useful feedback for me that the feature could be easier to discover 😅

**Comment by ericwangqing** [comment]
may we config to use a different dir path other than '.live-plugins' ?

**Comment by dkandalov** [comment]
Not at the moment (because it's hardcoded). What path would you like to use?

**Comment by ericwangqing** [comment]
something like <PROJECT_ROOT>/projects/intellij-plugin/src

**Comment by JG9A** [comment]
Hi @dkandalov 

Wanted to ask what is the proper way to share the plugins sources between users beside gits (we are blocked by company restrictions) ? 

Thanks 

p.s. Amazing Plugin!!!

**Comment by dkandalov** [comment]
@JG9A Thank you!
Depends on what you mean by "proper" :)

Since live plugins are just folders in the `live-plugin` folder (for me it's `~/Library/Application Support/JetBrains/IntelliJIdea2024.3/live-plugins`), it's the question of how to share the files.

As an option, you could probably use your company version control in each plugin folder or even have a single repo for all plugins.

**Comment by JG9A** [comment]
Hi @dkandalov tnx for the quick response.

Before asking I tried to copy my plugins to be managed by the git under my project root but I didn’t find a way to tell the live-plugin that this new folder is the folder that contains the plugins….

Probably I am missing something

Thanks

**Comment by dkandalov** [comment]
You can have project-specific plugins under `.live-plugins` folder in the project.

If plugins are shared across all projects (i.e. normal live plugins), they have to be in the predefined `live-plugins` folder which is located next to other IDE settings. For example, for me on macOS it's `~/Library/Application Support/JetBrains/IntelliJIdea2024.3/live-plugins`. One way to find this path is by doing `Copy Path` action on some file.

**Comment by JG9A** [comment]
Oh ok thanks will try that! 

And the .live-plugins folder must be a direct child folder of the project root? 

Thanks again

**Comment by dkandalov** [comment]
> And the .live-plugins folder must be a direct child folder of the project root?

Yes
