### ISSUE TITLE
I want use external dependency, like in IDE Scripting Console 

### ISSUE THREAD

**Issue by 1123Javayanglei** [dkandalov/live-plugin#129]

**Comment by dkandalov** [comment]
Hi. I'm not familiar with how IDE scripting console adds external dependencies and can't find it in the documentation.

With liveplugin you can add `// add-to-classpath` or `// depends-on-plugin` special comment after imports (there is also an intention available on alt+enter). E.g. see one of the built-in examples https://github.com/dkandalov/live-plugin/blob/master/plugin-examples/kotlin/additional-classpath/plugin.kts

**Comment by 1123Javayanglei** [comment]
> 

Thank you i will try it, Can i use maven dependencies ?

**Comment by 1123Javayanglei** [comment]
### ok,Thank you, but not use $HOME,juet only use absolute path
![image](https://user-images.githubusercontent.com/40049365/162350040-d63f1066-4e7d-487a-af29-3f33addd2121.png)

**Comment by 1123Javayanglei** [comment]
> In win10 i use  Windows Environment Variables replace $HOME, is ok

```kotlin
import liveplugin.*
import cn.hutool.core.convert.Convert


// add-to-classpath $HOMEDRIVE$HOMEPATH\.m2\repository\cn\hutool\hutool-all\5.8.0.M2\hutool-all-5.8.0.M2.jar



// absolute path
// C:\Users\tica\.m2\repository\cn\hutool\hutool-all\5.8.0.M2\hutool-all-5.8.0.M2.jar
// use Windows Environment Variables， $HOMEDRIVE$HOMEPATH = C:\Users\tica
// https://ss64.com/nt/syntax-variables.html
// $HOMEDRIVE$HOMEPATH\.m2\repository\cn\hutool\hutool-all\5.8.0.M2\hutool-all-5.8.0.M2.jar


val str = Convert.toStr("ok");

show(str)



```
