### ISSUE TITLE
View debugging info/errors?

### ISSUE THREAD

**Issue by UnbridledGames** [dkandalov/live-plugin#145]
Continuing to develop my plugin, but if there is an error that does not happen on startup (such as during a function execution) literally nothing happens, and I have no way of knowing why the action/etc failed to run. Is there a way to see errors that happen inside the plugin while it's running?

**Comment by dkandalov** [comment]
Hi. Sorry for the slow reply. 
This is similar to any other plugin. IDE will usually show a dialog with "IDE internal errors". But in some cases it will only log the stacktrace in the IDE log file or I've seen it silently ignoring the exception (it depends on how IDE code which integrate with handles errors). If you want to be sure all errors are displayed, you could wrap the code in try/catch and log it.

**Comment by UnbridledGames** [comment]
Yeah, only place I could find the info was in the main log file. Thanks.
