### ISSUE TITLE
access to kotlin psi classes, e.g. org.jetbrains.kotlin.psi.KtProperty

### ISSUE THREAD

**Issue by klaus7** [dkandalov/live-plugin#151]
Hello, I'm trying to implement a small "rearrange kotlin members" plugin. For this I need access to the psi classes of kotlin.

I tried to use the following line with no success:
```
// depends-on-plugin com.intellij.kotlin
```
Unfortunately still no access to kotlin psi classes.

**Comment by dkandalov** [comment]
Hi.

The short answer is `// depends-on-plugin org.jetbrains.kotlin` should work (see Kotlin examples bundled with LivePlugin, e.g. "kotlin-intention").

The long answer is that "org.jetbrains.kotlin" is the plugin id of Kotlin plugin (see https://github.com/JetBrains/intellij-community/blob/master/plugins/kotlin/plugin/resources/META-INF/plugin.xml). Unfortunately, AFAIK plugin ids are not displayed anywhere in IDE UI and are hard to guess. I often look up ids in "plugin.xml" of the plugin I need, but this is not ideal.

One option to fix it might be to have auto-completion after `depends-on-plugin` directive in LivePlugin, so you could ctrl-space and find the right plugin id. Plus some kind of inspection to highlight incorrect plugin ids. At the same time something like `@file:DependsOn` annotation in Kotlin script or kscript might be even better in case it gets a good IDE support one day.

**Comment by klaus7** [comment]
Thanks, ok, so my error was the "com." instead of the working "org.", I see. Yeah, I just guessed it actually. Should have looked into the kotlin examples before. Thanks also for your explanation.
