### ISSUE TITLE
Can I auto load specific non project plugins at startup?

### ISSUE THREAD

**Issue by davecazz** [dkandalov/live-plugin#157]
Hello, I love livePlugin, thanks for building this. 

Is there anyway to automatically load a plugin on startup without loading my the entire list of liveplugins?

**Comment by dkandalov** [comment]
Hi. Thank you 🙂

There is `isIdeStartup` variable available in the plugin context which can be used to skip some of the plugins on IDE startup. Similar to this example https://github.com/dkandalov/live-plugin/blob/master/plugin-examples/kotlin/ide-actions/plugin.kts#L21

**Comment by davecazz** [comment]
Thanks Dmitry!
