### ISSUE TITLE
Resolving transitive dependencies to overcome NoClassDefFoundError

### ISSUE THREAD

**Issue by shpakkrll** [dkandalov/live-plugin#167]
Simplicity is great, but there is a time cost of finding ways to do same things you're used to.

Having `// add-to-classpath` works great for _fat_ JARs (libraries that were build with `gradle shadowJar`)
Regular dependencies that are using other transitive dependencies I found to be a problem. It throws `NoClassDefFoundError` when classpath JAR is referencing another library.

It also means that sharing your cool live plugins with the team and adding it to version control systems would require to include those _fat_ JARs as well, otherwise everybody would require to build fat JARs on their local to use the plugin. Also those JAR files are big and could take more space then project itself.

Is there a way to auto resolve transitive dependencies by the live plugin?
Kudos!

**Comment by dkandalov** [comment]
Yes, adding dependencies is a bit of a pain :( 
I hope eventually Kotlin script will be mature enough and dependencies could be added via file annotations https://kotlinlang.org/docs/custom-script-deps-tutorial.html 
For Groovy something like Grape should work http://docs.groovy-lang.org/latest/html/documentation/grape.html

What I'm doing at the moment is adding something like `// add-to-classpath $PLUGIN_PATH/libs/*.jar` and using "Download Library from Maven Repository" action which is available in "Project Structure" when manually adding a library. It can download maven artifact with transitive dependencies to any folder.

**Comment by shpakkrll** [comment]
That will simplify things a bit as well. Thanks
