### ISSUE TITLE
How to rerun plugins under .live-plugins folder

### ISSUE THREAD

**Issue by shpakkrll** [dkandalov/live-plugin#168]
Sometimes plugins that are included directly in the project under the  `/.live-plugins` folder stop working.
Does reruning project's plugins require full IntelliJ reload or there is a way to run those plugins again as its done in LivePlugins Tab?

**Comment by dkandalov** [comment]
There are actions to rerun and unload plugins. For project-specific plugins they can be invoked:
 - in the context popup menu in the project view, right click on the folder/file should
 - in the context popup menu in the editor when plugin related file is open
 - via action search, when the current context is live plugin, e.g. navigate to plugin files in the project view, open "Find Actions..." (cmd+shift+A), type "run plugin" or "unload plugin".

Thank you for asking the question! It prompts me do to something about it (eventually). I admit though it can be tricky to find these actions and they're not too easy to discover. 

Probably, the best solution is to make live plugins use run configs similar to how other programs and scripts are executed in IDE 🤔

**Comment by shpakkrll** [comment]
Visibility matters:) Everything works, thanks
