### ISSUE TITLE
How to register a Line Marker?

### ISSUE THREAD

**Issue by PedroAugustoRamalhoDuarte** [dkandalov/live-plugin#174]
Thanks for the awesome library.

I search i little bit, but i cannot get how to make Gutter/Line Marker to work with live plugin, how i can achieve that? 

https://plugins.jetbrains.com/docs/intellij/line-marker-provider.html#register-the-line-marker-provider

**Comment by dkandalov** [comment]
Thank you!

It's usually possible to find extension points in Java/Kotlin source code (e.g. https://github.com/JetBrains/intellij-community/blob/4e6d54bc73ddaab5af086a07fd86d0beda746ca9/platform/lang-api/src/com/intellij/codeInsight/daemon/LineMarkerProviders.java#L13) and directly register extensions with `pluginDisposable` for reloadability.

Unfortunately, language extension points are for some reason tied plugin descriptor and need something like this:
```
import com.intellij.codeInsight.daemon.LineMarkerInfo
import com.intellij.codeInsight.daemon.LineMarkerProvider
import com.intellij.codeInsight.daemon.LineMarkerProviders
import com.intellij.icons.AllIcons.Ide.Gift
import com.intellij.lang.LanguageExtensionPoint
import com.intellij.openapi.editor.markup.GutterIconRenderer
import com.intellij.openapi.extensions.DefaultPluginDescriptor
import com.intellij.openapi.extensions.PluginId
import com.intellij.psi.PsiElement

val pluginDescriptor = DefaultPluginDescriptor(PluginId.getId("LivePlugin"), MyMarkerProvider::class.java.classLoader)
val extensionPoint = LanguageExtensionPoint<LineMarkerProvider>("kotlin", "Plugin\$MyMarkerProvider", pluginDescriptor)
LineMarkerProviders.EP_NAME.point.registerExtension(extensionPoint, pluginDisposable)

class MyMarkerProvider : LineMarkerProvider {
    override fun getLineMarkerInfo(element: PsiElement) =
        if (!element.text.contains("foo")) null
        else LineMarkerInfo(element, element.textRange, Gift, null, null, GutterIconRenderer.Alignment.CENTER) { "" }
}
```

Overall, it's all about IntelliJ API design to be more usable without xml, etc.

**Comment by PedroAugustoRamalhoDuarte** [comment]
Thanks very much it works very well
