### ISSUE TITLE
changeGlobalVar does not work in Kotlin

### ISSUE THREAD

**Issue by DasGandlaf** [dkandalov/live-plugin#180]
Hey, this plugin is amazing!

I'm trying to unsubscribe the old CaretListener on plugin re-run.

I can't get changeGlobalVar() to work in Kotlin, `previous` is always null:
```kotlin
changeGlobalVar<CaretListener>("caretListener", object:Closure<CaretListener>(this) {
    fun doCall(previous: CaretListener?): CaretListener {
        show(previous) // <-- Always null

        return object : CaretListener {}
    }
})
```
(Defining the Closure in any other way caused type errors for me)

While this Groovy code works perfectly fine:
```groovy
changeGlobalVar("caretListener"){ previous ->
    show(previous) // <- This is correct
    
    new CaretListener() {}
}
```

Also the `changeGlobalVar()` return value is in Kotlin: `Plugin$listener$1$doCall$1@34d81bc2`, in Groovy: `plugin$1@b083066`

Any ideas to fix this? I appreciate the help :)

**Comment by dkandalov** [comment]
Hi. Thank you!

Slightly modified version of the Kotlin code you mentioned seems to work for me 🤔 
```
PluginUtil.changeGlobalVar<String>("foo", object : Closure<String>(this) {
    fun doCall(previous: String?): String {
        show(previous) // <-- Always null
        return "foo ${Instant.now()}"
    }
})
```

Overall, `changeGlobalVar` was never a good idea though.

For cleanup on plugin rerun, I would use `pluginDisposable`, e.g.
```
val caretListener = ...
pluginDisposable.whenDisposed {
    // unregister caretListener
}
```

For transferring data between plugin reruns (by serialising/deserialising some objects) a file might be good enough.

**Comment by DasGandlaf** [comment]
Thank you! This is a much better solution.
