### ISSUE TITLE
plugin cause idea console soft wrap not work

### ISSUE THREAD

**Issue by towith** [dkandalov/live-plugin#182]
- output is not soft wrapped even when the soft wrap option is on if this plugin is enabled.
- If i disable this plugin, then the soft wrap of console behave normally
- Thanks for your great plugin
- Live-Plugin version 0.8.8 beta, idea version 2024.1.4
![image](https://github.com/dkandalov/live-plugin/assets/9798922/df231761-5f47-4b77-935c-cc88673f06a8)

**Comment by dkandalov** [comment]
Hm, I never had this problem with soft wrap. Just tried with spring boot as in the screenshot and it works fine (same version of IDE and plugin).

My guess would be there is a live-plugin (the one you might have writen) and it's silently failing affecting soft wrap somehow 🤔 Do you see any errors in IntelliJ log?

**Comment by towith** [comment]
Appreciate for you reply so quickly. Sorry, I have test this again, disable live-plugin, and the soft wrap problem still exists.
I have forgotten what i have done to make it work normally however, But it seems not an issue related to live-plugin, so i shall close this issue, thanks

**Comment by dkandalov** [comment]
No problem, it happened to me as well in the past 🙂

In case it helps, one of the approaches is to do a "binary" search by disabling a bulk of plugins and checking if the issue still exists (because things like that are most likely caused by plugins).

**Comment by towith** [comment]
> In case it helps, one of the approaches is to do a "binary" search by disabling a bulk of plugins and checking if the issue still exists (because things like that are most likely caused by plugins).

Ok, binary search, I know what you mean, thanks for the advice, you are really nice 👍
