### ISSUE TITLE
Highlight and code completion is not working in plugin.kts

### ISSUE THREAD

**Issue by grsky360** [dkandalov/live-plugin#185]
Idea version: 2024.2

Highlight and code completion is not working in plugin.kts, but working in live-plugins.kts

**Comment by ShlomoAlon** [comment]
same issue for me here except it's not working live-plugins.kts either

**Comment by dkandalov** [comment]
Sorry, for the slow reply. I have the same issue :(

It looks like 2024.2 broke many things and I'm slowly fixing them.
Highlight and code completion is the next one.

**Comment by dkandalov** [comment]
This should be partially fixed in the plugin version 0.9.0.

Kotlin script has changed the way it's matching script files based on regex and how it's resolving dependencies of the script. All of that is hard to debug unfortunately :(

**Comment by grsky360** [comment]
The highlight and code completion is working, but cannot be compiled anymore...
#186

**Comment by scroogemcfawk** [comment]
Hi, I faced the following issue:
The plugins compile and run normally, but syntax highlighting and code completion do not work in .kts plugin files.
Everything works in .groovy files.

Idea info:
```
IntelliJ IDEA 2024.3.2.2 (Ultimate Edition)
Build #IU-243.23654.189, built on January 29, 2025
Toolkit: sun.awt.X11.XToolkit
Linux 5.15.173-1-manjaro
Kotlin plugin: K2 mode
GC: G1 Young Generation, G1 Concurrent GC, G1 Old Generation
Memory: 6000M
Cores: 24
Registry:
  java.completion.show.constructors=true
  ide.experimental.ui=true
  idea.ignore.disabled.plugins=true
  jvm.dfa.analysis.ui.security.analysis.window.was.shown=true
Non-Bundled Plugins:
  com.intellij.notebooks.core (243.23654.153)
  com.darkyen.darkyenustimetracker (1.5.3)
  com.jetbrains.space (243.23654.19)
  IdeaVIM (2.18.1)
  org.jetbrains.jumpToLine (0.1.17)
  com.cg.altair-plugin (2.4.0)
  AntSupport (243.23654.117)
  com.jetbrains.jax.ws (243.21565.129)
  String Manipulation (9.15.0)
  Key Promoter X (2024.2.2)
  intellij.jupyter (243.23654.117)
  org.jetbrains.plugins.kotlin.jupyter (243.23654.153)
  izhangzhihao.rainbow.brackets (2024.2.8-241)
  ru.adelf.idea.dotenv (2024.3)
  LivePlugin (0.9.5 beta)
Kotlin: 243.23654.189-IJ
Current Desktop: GNOME
```
