### ISSUE TITLE
Updated Scala Libraries

### ISSUE THREAD

**Issue by hsyed** [dkandalov/live-plugin#51]
Howdy,

Nice plugin. However for Scala there should be some way of tracking the latest libraries. Manually copying in compiler,library, reflect, javap and actor does not do the trick.

Using the 2.10.2 libraries in LivePlugin against stuff compiled against 2.11.7 doesn't work reliably ;(

Cheers

Hassan

**Comment by dkandalov** [comment]
Hello,

I updated scala core libraries to 2.11("scala-library", "scala-compiler", "scala-reflect", "scala-swing", "scala-partest", "scala-actors", "scalap") and will release new version of the plugin this week.

Not sure if it's worth adding other jars, you can always add more using add-to-classpath comment https://github.com/dkandalov/live-plugin/blob/master/plugin_examples/liveplugin/pluginexamples/additionalClasspath/plugin.groovy#L5

**Comment by hsyed** [comment]
Heya dude, 

Thanks. I just came back to do some work on plugins now.

The scala swing URL is broken. it's best to stick to the base dependencies. Perhaps allows users to point to a lib directory or something for other dependencies ? 

Cheers

Hassan

**Comment by dkandalov** [comment]
Hi,

I agree about base dependencies. Will remove everything non-core in the next release.

Yes, you can add external libs with comment like in this example https://github.com/dkandalov/live-plugin/blob/master/plugin_examples/liveplugin/pluginexamples/additionalClasspath/plugin.groovy

Regards,
Dmitry
