### ISSUE TITLE
A little addition to plugin example

### ISSUE THREAD

**Issue by 3363686** [dkandalov/live-plugin#53]
When using 'showInConsole()' as in utilExample, new console tab is opened on every call.
I think it's better to mention that if somebody wants to output "...." together with "Hello console", then the lines

// shows text in console
showInConsole("Hello console", "my console", project)
showInConsole("....", "my console", project)

should be changed to something like this

ConsoleView console = showInConsole("Hello console", "my console", project)
console.print( "....", Console.guessContentTypeOf("....") )

(also needs
import com.intellij.execution.ui.ConsoleView
import liveplugin.implementation.Console
)

Alexei

**Comment by dkandalov** [comment]
Thank you, I'll add this to example.

**Comment by dkandalov** [comment]
Updated. Thanks again and please feel free to give a shout if something is confusing or doesn't work.
