### ISSUE TITLE
"tab" not work with IntelliJ 15 

### ISSUE THREAD

**Issue by icanth** [dkandalov/live-plugin#57]
Hello, when using intellij 15 with your newest plugin, i find that running the  "Tab" example will throw expections.

the "tab" exmaple:
Template completion on "Tab" - simplistic prototype for auto-completion on tab key (in case built-in live templates are not enough)
https://gist.github.com/dkandalov/5222759

the log error detial: 
11:22:42 PM MissingMethodException
            No signature of method: plugin$_run_closure1.doCall() is applicable for argument types: (liveplugin.implementation.ActionWrapper$Context) values: [liveplugin.implementation.ActionWrapper$Context@3c559442]
            Possible solutions: doCall(com.intellij.openapi.actionSystem.AnActionEvent, com.intellij.openapi.actionSystem.AnAction), findAll(), findAll(), isCase(java.lang.Object), isCase(java.lang.Object)

**Comment by dkandalov** [comment]
Thank you!
I confirm it doesn't work any more. I'll look into it today.

**Comment by dkandalov** [comment]
I uploaded new version of plugin (0.5.5 beta) with the fix and updated gist with the example (there was API change for wrapping actions btw).
