### ISSUE TITLE
Is there a way to plug in to extension points?

### ISSUE THREAD

**Issue by vjpr** [dkandalov/live-plugin#61]
See http://www.jetbrains.org/intellij/sdk/docs/basics/plugin_structure/plugin_extensions_and_extension_points.html

**Comment by dkandalov** [comment]
Adding extension to extension point, yes.
See [wiki](https://github.com/dkandalov/live-plugin/wiki/Console-filtering) or [Console.groovy source code](https://github.com/dkandalov/live-plugin/blob/master/src_groovy/liveplugin/implementation/Console.groovy#L48).

Adding new extension point I never tried.
Something like this method might work `com.intellij.openapi.extensions.impl.ExtensionsAreaImpl#registerExtensionPoint(com.intellij.openapi.extensions.impl.ExtensionPointImpl)`.
Or may be using `com.intellij.openapi.extensions.ExtensionsArea` interface (this is more xml oriented API though).

Overall IJ APIs were not designed for reloadability, so if you do something interesting, please send a code snippet :)
