### ISSUE TITLE
Reference contributor

### ISSUE THREAD

**Issue by aarcangeli** [dkandalov/live-plugin#66]
Hi,
would be great if there was the ability to add a custom reference contributor in order to support the "Go to Declaration" and "Find Usages".

In normal plugins I use the following tag:
`<psi.referenceContributor language="JAVA" implementation="myPackage.BlahBlahCotributor"/>`

**Comment by kreiger** [comment]
It's not pretty, but i managed to hack this in a plugin like so:

```
PsiReferenceProvider referenceProvider = ...

def referenceProvidersRegistry = ReferenceProvidersRegistry.getInstance() as ReferenceProvidersRegistryImpl
referenceProvidersRegistry.myRegistrars.remove(JavaLanguage.INSTANCE)
def registrar = referenceProvidersRegistry.getRegistrar(JavaLanguage.INSTANCE)
registrar.myInitialized = false
registrar.registerReferenceProvider(PsiJavaPatterns.literalExpression(), referenceProvider)
registrar.markInitialized()
```

**Comment by mrkoopa** [comment]
Awesome
Thank you very much
