### ISSUE TITLE
Exception not thrown?

### ISSUE THREAD

**Issue by hari-rangarajan** [dkandalov/live-plugin#68]
I attempted a simple variation on the console filter plugin: It did work. I made a few changes to the code and I think it is now hitting a run-time exception that is swallowed. No console shows up with the code below. Infact, subsequently, running any other project also never shows the console. Can you please try this? Thanks!

import com.intellij.ide.scratch.RootType
import com.intellij.ide.scratch.ScratchFileActions
import com.intellij.ide.scratch.ScratchFileService
import com.intellij.ide.scratch.ScratchRootType
import com.intellij.lang.Language
import com.intellij.openapi.application.ApplicationManager
import com.intellij.openapi.command.WriteCommandAction
import com.intellij.openapi.editor.Document
import com.intellij.openapi.fileEditor.FileDocumentManager
import com.intellij.openapi.fileEditor.FileEditor
import com.intellij.openapi.fileEditor.FileEditorManager
import com.intellij.openapi.vfs.VirtualFile
import com.intellij.openapi.vfs.VirtualFileManager

import static liveplugin.PluginUtil.*

import com.intellij.execution.filters.ConsoleInputFilterProvider
import com.intellij.execution.filters.InputFilter
import com.intellij.execution.ui.ConsoleViewContentType as ContentType
import com.intellij.openapi.project.Project
import com.intellij.openapi.util.Pair
import org.jetbrains.annotations.NotNull

import static liveplugin.PluginUtil.*
import com.intellij.openapi.extensions.Extensions
import static com.intellij.execution.filters.ConsoleInputFilterProvider.*
import static com.intellij.execution.ui.ConsoleViewContentType.NORMAL_OUTPUT

if (isIdeStartup) return

def findOrCreateVirtualFile(String url) {
    ScratchFileService.getInstance().findFile(RootType.findById())
    def virtualFileExist = VirtualFileManager.getInstance().findFileByUrl(url)
    if (virtualFileExist != null) virtualFileExist
    
    return ScratchRootType.getInstance().createScratchFile(
            project,
            url, 
            Language.ANY, '', ScratchFileService.Option.create_if_missing)
}

def teeToScratch() {
    def virtualFile = findOrCreateVirtualFile('ConsoleOut:' + project.name)
    def document = FileDocumentManager.getInstance().getDocument(virtualFile)

    new InputFilter() {
        @Override
        List<Pair<String, ContentType>> applyFilter(String consoleText, ContentType contentType) {
            Runnable runnable = new Runnable() {
                @Override
                public void run() {
                    document.insertString(document.textLength, consoleText)
                }
            }
            WriteCommandAction.runWriteCommandAction(project, runnable)
            [new Pair(consoleText, contentType)]
        }
    }
}

def createInputFilterProvider() {
	new ConsoleInputFilterProvider() {
		@Override InputFilter[] getDefaultFilters(@NotNull Project project) {
			[teeToScratch()]
		}
	}
}

def extensionPoint = Extensions.rootArea.getExtensionPoint(INPUT_FILTER_PROVIDERS)
def inputFilterProvider = changeGlobalVar("myConsoleFilter") { lastInputFilterProvider ->
	if (lastInputFilterProvider != null && extensionPoint.hasExtension(lastInputFilterProvider)) {
		extensionPoint.unregisterExtension(lastInputFilterProvider)
	}
	createInputFilterProvider()
}
extensionPoint.registerExtension(inputFilterProvider)

show("Installed console filter")
def console = showInConsole("START-----\n", project)
console.print("INFO - which will be invisible\n", NORMAL_OUTPUT)
console.print("ERROR - beautified java.lang.NullPointerException\n", NORMAL_OUTPUT)
console.print("-----END\n", NORMAL_OUTPUT)

**Comment by hari-rangarajan** [comment]
Actually, I managed to find the error in the IDE logs. It does show up as PluginManager. Wonder if you can catch this and popup an error?


017-03-22 17:47:26,815 [5190568]  ERROR - llij.ide.plugins.PluginManager - Argument for @NotNull parameter 'id' of com/intellij/ide/scratch/RootType.findById must not be null 
java.lang.IllegalArgumentException: Argument for @NotNull parameter 'id' of com/intellij/ide/scratch/RootType.findById must not be null
	at com.intellij.ide.scratch.RootType.findById(RootType.java)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at org.codehaus.groovy.runtime.callsite.StaticMetaMethodSite.invoke(StaticMetaMethodSite.java:46)
	at org.codehaus.groovy.runtime.callsite.StaticMetaMethodSite.call(StaticMetaMethodSite.java:91)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:117)
	at plugin.findOrCreateVirtualFile(plugin.groovy:32)
	at plugin$findOrCreateVirtualFile.callCurrent(Unknown Source)
	at plugin.teeToScratch(plugin.groovy:43)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)

**Comment by dkandalov** [comment]
Hello,

Sorry it took ages to reply (I managed to unwatch all my repositories and noticed this only couple days ago).

In case this is helpful, the reason IDE throws an exception is because `RootType.findById()` function call is missing an argument (see [IJ source code](https://github.com/JetBrains/intellij-community/blob/e06c3a950fd9dd73554b5e390a3d9e6cf3680d3c/platform/lang-impl/src/com/intellij/ide/scratch/RootType.java#L49)). So groovy decides to put `null`, IDE sees that argument is null and throws assertion exception.

If I run `RootType.findById()` as top level expression in its own plugin, then I can see exception pops up in a console. I suspect you didn't see the exception popup because the code runs inside `inputFilterProvider` extension point. I.e. it runs outside of liveplugin and it doesn't control exception handling.

Give a shout if you need any help, I'm now watching this repository again and should receive email for every comment :)
