### ISSUE TITLE
Kotlin highlighting and IDE assistance

### ISSUE THREAD

**Issue by sirgl** [dkandalov/live-plugin#75]
Some references are resolved properly, but others are not. Probably it may be problem of IDE, but not plugin. 

IDEA Ultimate 2017.3

<img width="755" alt="screen shot 2017-12-06 at 11 01 13" src="https://user-images.githubusercontent.com/11944514/33643989-da052bda-da74-11e7-8747-acce5e693bf2.png">

**Comment by alshain** [comment]
In general, I don't seem to get completion in Kotlin, even though I added LivePlugin and IntelliJ jars to my project:

![image](https://user-images.githubusercontent.com/349397/44307192-42762780-a39e-11e8-9382-54f60aaffc9d.png)

**Comment by jbarr21** [comment]
I'm also seeing this, IntelliJ 2018.3 Community with Kotlin 1.3.21

**Comment by dkandalov** [comment]
This was fixed in v0.6.3 and should be working in IntelliJ starting from 2019.1.
Sorry it took ages to fix.

**Comment by alshain** [comment]
@dkandalov yep, looking good so far. Thanks a lot!
