### ISSUE TITLE
Unable to run any plugins, Run action disabled

### ISSUE THREAD

**Issue by OndrejSpanel** [dkandalov/live-plugin#76]
I have just installed the plugin, as the idea seams really promissing to me. The idea.log confirms the plugin is loaded:

> 2017-12-11 14:08:22,099 [   2640]   INFO - llij.ide.plugins.PluginManager - Loaded custom plugins: .... LivePlugin (0.6.0 beta), ...

The plugin menu can be seen, but both the Run menu action and the Run icon are disabled (gray).

![image](https://user-images.githubusercontent.com/6927223/33832696-60f92a90-de7d-11e7-8292-68a71d2f65ea.png)

My IntelliJ version information is:
> IntelliJ IDEA 2017.3.1 (Ultimate Edition)
> Build #IU-173.3942.15, built on December 6, 2017
> JRE: 1.8.0_152-release-1024-b8 amd64
> JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
> Windows 10 10.0

**Comment by dkandalov** [comment]
Thanks a lot reporting this.
I think it might be an issue with windows vs unix paths. Will try to fix it later today.

**Comment by OndrejSpanel** [comment]
Thanks for quick response.

Some more messages from the log, probably not relevant:

> 2017-12-11 14:08:27,514 [   8055]   INFO -                     LivePlugin - Enabled junit panel output for integration tests 
> 2017-12-11 14:08:32,435 [  12976]   WARN - openapi.wm.impl.ToolWindowImpl - ToolWindow icons should be 13x13. Please fix ToolWindow (ID:  Plugins) or icon jar:file:/D:/Users/Ondra/.IntelliJIdea2017.3/config/plugins/LivePlugin/lib/LivePlugin.jar!/liveplugin/plugin-toolwindow-icon.png

**Comment by dkandalov** [comment]
Run actions should be enabled in version 0.6.1.
(The toolwindow icon is not related but should also be fixed now.)

**Comment by OndrejSpanel** [comment]
I confirm it is working fine now. Many thanks for the quick fix.
