### ISSUE TITLE
Is there an API-Point to inject Program arguments as in Run/Debug Configurations dialog for applications ?

### ISSUE THREAD

**Issue by 573** [dkandalov/live-plugin#91]
Even more great would be a simplistic example (snippet).

I reckon I would use "Scripting a macros" as starting point.

EDIT:
All I found so far was https://upsource.jetbrains.com/idea-ce/file/idea-ce-dcdbb638faddbded22ec187e38c01a6d4ea8b309/platform/lang-impl/src/com/intellij/execution/impl/RunnerAndConfigurationSettingsImpl.kt?nav=3701:3731&findUsages=/platform/lang-api/src/com/intellij/execution/configurations/ConfigurationPerRunnerSettings.java:888:918:-1 or https://github.com/jskierbi/intellij-ce-playground and I am lost already.

**Comment by dkandalov** [comment]
Sorry for a very slow reply but I guess it's better late than never.

I created this gist showing how to use run configs from IntelliJ API https://gist.github.com/dkandalov/38848adc0ab62a7e4f2f56eb7ce13f79

There are examples for Java, Kotlin, Gradle and JUnit runners. If you're using some other language, you'll need to add dependency on its plugin via `depends-on-plugin` and find its run configuration class similar to the examples.
