### ISSUE TITLE
LivePlugin plugin code seems not compliant with intellij 2019.1

### ISSUE THREAD

**Issue by gorru** [dkandalov/live-plugin#93]
import com.intellij.openapi.actionSystem.AnActionEvent
import static liveplugin.PluginUtil.*

Both lines report "Cannot resolve symbol"

Thanks in advance

**Comment by dkandalov** [comment]
This was fixed in v0.6.3 and should be working in IntelliJ 2019.1.

**Comment by gorru** [comment]
Thank you very much!
I confirm that it works
