### ISSUE TITLE
Tool windows gets empty after adding a new plugin

### ISSUE THREAD

**Issue by krasa** [dkandalov/live-plugin#96]
It looks like this:
![image](https://user-images.githubusercontent.com/1160875/59296738-fb3b8900-8c86-11e9-96e9-d8252c6765ff.png)

Resizing or hovering over buttons fixes it:

![image](https://user-images.githubusercontent.com/1160875/59296823-23c38300-8c87-11e9-9819-33d07d9ace1a.png)

```
live-plugin  0.6.3 beta

IntelliJ IDEA 2019.2 EAP (Ultimate Edition)
Build #IU-192.4787.16, built on June 6, 2019
Runtime version: 11.0.3+12-b281.38 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
```

**Comment by krasa** [comment]
Deleting has the same effect. (and with proper 0.6.3 beta)

**Comment by dkandalov** [comment]
I think this also happens in older versions of IJ (e.g. in 2019.1) but I could only reproduce it with a task running in background, e.g.
<img width="477" alt="Screenshot 2019-06-12 at 22 38 26" src="https://user-images.githubusercontent.com/28375/59388121-e2a0a100-8d62-11e9-9599-9cdba208f250.png">

**Comment by krasa** [comment]
Yeah I think it was there from the beginning. 
I can reproduce it without it, almost always, but not in pom.xml files, plaintext works great.

**Comment by krasa** [comment]
If I am long enough in the Add dialog, so that this popup disappears:
![image](https://user-images.githubusercontent.com/1160875/59422534-d6ebc380-8dd0-11e9-996d-52b1810adf21.png)
then it works fine, because as the popup gets automatically shown, the tool window gets repainted with it.

I could try to fix it if you want.

**Comment by dkandalov** [comment]
Sure, if you want give it a go 👍 

I think fundamentally the problem is that the way file tree is created in `PluginToolWindow` is just a hack. My plan was to look at the latest IJ API to find what is the "right" way to do it these days but I don't mind any other fixes :)

**Comment by krasa** [comment]
Why don't you use LivePluginAppComponent#livePluginsPath as the tree root + filter to get rid of .idea folder? It would solve everything.

**Comment by dkandalov** [comment]
If you mean `addRoots` function, then as the comment below says it's because of the case when there is only one plugin, the tree was doing something funny and basically automatically changing root to one level down. IIRC it was true in 2013, might not be true anymore though.
```
        private fun addRoots(descriptor: FileChooserDescriptor, virtualFiles: List<VirtualFile>) {
            // Adding file parent is a hack to suppress size == 1 checks in com.intellij.openapi.fileChooser.ex.RootFileElement.
            // Otherwise, if there is only one plugin, tree will show files in plugin directory instead of plugin folder.
            // (Note that this code is also used by "Copy from Path" action.)
            if (virtualFiles.size == 1) {
                val parent = virtualFiles[0].parent
                descriptor.roots = if (parent != null) listOf(parent) else virtualFiles
            } else {
                descriptor.roots = virtualFiles
            }
        }
```

**Comment by krasa** [comment]
Yes, and seemed to work fine now.

**Comment by dkandalov** [comment]
Hm, to me it looks like it hasn't changed 🤔 
<img width="271" alt="Screenshot 2019-06-14 at 17 02 58" src="https://user-images.githubusercontent.com/28375/59522398-835ba180-8ec6-11e9-8275-29b2cc413319.png">
<img width="268" alt="Screenshot 2019-06-14 at 17 04 12" src="https://user-images.githubusercontent.com/28375/59522399-835ba180-8ec6-11e9-83f3-86f5c71d0318.png">

**Comment by dkandalov** [comment]
Actually, what you suggested look like this
- no plugins <img width="270" alt="Screenshot 2019-06-14 at 17 25 05" src="https://user-images.githubusercontent.com/28375/59523511-71c7c900-8ec9-11e9-94f8-9721ee460420.png">
- one plugin <img width="271" alt="Screenshot 2019-06-14 at 17 25 19" src="https://user-images.githubusercontent.com/28375/59523524-77251380-8ec9-11e9-9602-aa27c7f17ed9.png">

**Comment by krasa** [comment]
What I did:
` descriptor.setRoots(VfsUtil.findFile(Paths.get(livePluginsPath),true))` 
instead of
`PluginToolWindowManager.addRoots(descriptor, virtualFiles)`

looked totally the same as the current solution. I will check other IDE versions.

**Comment by krasa** [comment]
works fine on 2018.3, maybe OS dependant?

 ![lp](https://user-images.githubusercontent.com/1160875/59532743-e6126480-8ee9-11e9-95d3-786292bc5d0c.gif)

**Comment by krasa** [comment]
This is what I did:
 https://github.com/dkandalov/live-plugin/compare/master...krasa:treeFlicker2?expand=1

**Comment by krasa** [comment]
Well, I reproduced this, several times, but only in sandbox
![image](https://user-images.githubusercontent.com/1160875/59536074-f975fd80-8ef2-11e9-858c-7eea9ad2341c.png)
there were plugins shown after start, but then just disappeared. After that the tree did not work at all.

**Comment by krasa** [comment]
I think the cause was that the root did not exist. All fixed now.

**Comment by krasa** [comment]
Ok I know where was the problem. I found a nice little method `VfsUtil.findFile(path, true)`, but it returns a VirtualFile even for non existing directory (both #exists and #valid return true) - looks like a bug in IJ... Gradle or something must have deleted my directory, so the tree had it's root, but the root folder did not really exist, and when it got created it did not make a difference.

**Comment by krasa** [comment]
https://user-images.githubusercontent.com/28375/59522398-835ba180-8ec6-11e9-8275-29b2cc413319.png
That was caused only by not disabling the action when there are no plugins.
